### ISSUE TITLE
add a UMD output

### ISSUE THREAD

**Issue by odoe** [Esri/esri-proj-codes#13]
Was trying to use this in a simple demo app (jsbin, codepen), but there wasn't able to use it with the ArcGIS API for JS because there is no UMD output.

It would be useful as secondary output, especially now that we have the projection engine client side in the JSAPI.

**Comment by jgravois** [comment]
hey @odoe! can you give what i just pushed to the [`umd`](https://github.com/Esri/proj-codes/blob/9cfb40870f345477a07b6b0d1dd8eade2764acd5/index.js) branch a test?

another option would be to rewrite in ES6 and use rollup or something to bundle _all_ the codes in a UMD.

**Comment by jgravois** [comment]
inbox zero.
