### ISSUE TITLE
new, probably superior raw data source

### ISSUE THREAD

**Issue by jgravois** [Esri/esri-proj-codes#14]
https://github.com/Esri/projection-engine-db-doc/

**Comment by jgravois** [comment]
i confirmed today that the repo above indeed contains a comprehensive canonical list of current, code-changed and deprecated coordinate systems.

as much fun as we've been having scraping public doc and doing diffs manually, my gut reaction is that we'd be better off helping the projection team abuse npm than continuing to do it on our own.

@dmfenton, what do you think?

**Comment by dmfenton** [comment]
I'd love to hand this off to the projection team.

**Comment by jgravois** [comment]
https://github.com/Esri/projection-engine-db-doc/pull/6
