### ISSUE TITLE
102645 is undefined

### ISSUE THREAD

**Issue by rgwozdz** [Esri/esri-proj-codes#15]
Tried inputing [102645](http://spatialreference.org/ref/esri/nad-1983-stateplane-california-v-fips-0405-feet/), but returned undefined.

**Comment by jgravois** [comment]
you should be using the EPSG wkid [`2229`](http://epsg.io/2229) instead.

i think its actually a quite common scenario that we (Esri) define a spatial ref and give it an `id` (> 32767) only to abandon it later once the crs is 'officially' adopted by oil and gas producers.

([source](https://youtu.be/6tmDxTAjux0?t=8m18s))
