### ISSUE TITLE
Update list of Geographic coordinate systems

### ISSUE THREAD

**Issue by don-vip** [Esri/esri-proj-codes#8]
I count **774** projections here:
http://resources.arcgis.com/en/help/arcgis-rest-api/index.html#/Geographic_coordinate_systems/02r300000105000000/

but only **675** in `geographic.json`:
https://raw.githubusercontent.com/Esri/esri-proj-codes/master/geographic.json

**Comment by jgravois** [comment]
thanks for reporting.

i've published [`v1.0.2`](https://github.com/Esri/esri-proj-codes/releases/tag/v1.0.2) to GitHub (and [npm](https://www.npmjs.com/package/esri-proj-codes)) with new projection codes for ArcGIS 10.5.  let me know if you have any trouble with the new release.
